// <auto-generated />
using Kolokwium2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    partial class WorkshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2.Entities.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCar"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.HasKey("IdCar");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            IdCar = 1,
                            Make = "BMW",
                            ProductionYear = 2004
                        },
                        new
                        {
                            IdCar = 2,
                            Make = "Fiat",
                            ProductionYear = 2014
                        });
                });

            modelBuilder.Entity("Kolokwium2.Entities.Car_Person", b =>
                {
                    b.Property<int>("IdCar")
                        .HasColumnType("int");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<bool>("MainOwner")
                        .HasColumnType("bit");

                    b.HasKey("IdCar", "IdPerson");

                    b.HasIndex("IdPerson");

                    b.ToTable("Car_Person", (string)null);

                    b.HasData(
                        new
                        {
                            IdCar = 1,
                            IdPerson = 1,
                            MainOwner = true
                        },
                        new
                        {
                            IdCar = 2,
                            IdPerson = 2,
                            MainOwner = false
                        });
                });

            modelBuilder.Entity("Kolokwium2.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"));

                    b.Property<string>("DrivingLicense")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdPerson");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            Name = "A",
                            Surname = "B"
                        },
                        new
                        {
                            IdPerson = 2,
                            DrivingLicense = "ADSA",
                            Name = "C",
                            Surname = "D"
                        });
                });

            modelBuilder.Entity("Kolokwium2.Entities.Car_Person", b =>
                {
                    b.HasOne("Kolokwium2.Entities.Car", "Car")
                        .WithMany("CarPersons")
                        .HasForeignKey("IdCar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Entities.Person", "Person")
                        .WithMany("CarPersons")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Kolokwium2.Entities.Car", b =>
                {
                    b.Navigation("CarPersons");
                });

            modelBuilder.Entity("Kolokwium2.Entities.Person", b =>
                {
                    b.Navigation("CarPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
